- name: Create web server image
  hosts: all
  remote_user: root
  become: true
  tasks:
   - name: Build Image
     docker_image:
       path: /root/
       name: webserverimage
       repository: devopstest777/webserverimage:latest
       force_tag: yes
       source: local
