- name: Pull the Centos 7 image
  hosts: all
  become: true
  tasks:
   - name: Start docker service
     service:
       name: docker
       state: started
   - name: pull
     docker_image:
       name: centos:7
